services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data/_data:/home/node/.n8n
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - FB_PAGE_TOKEN=${FB_PAGE_TOKEN}
      - FB_PAGE_ID=${FB_PAGE_ID}
      - IG_USER_ID=${IG_USER_ID}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
